"""
Django settings for wharttest_django project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Added for environment variables
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# 处理HuggingFace环境变量的相对路径
# 将.env文件中的相对路径转换为绝对路径
def setup_huggingface_env():
    """设置HuggingFace环境变量，处理相对路径"""
    hf_vars = ['HF_HOME', 'HF_HUB_CACHE', 'SENTENCE_TRANSFORMERS_HOME']

    for var in hf_vars:
        value = os.environ.get(var)
        if value and not os.path.isabs(value):
            # 如果是相对路径，转换为绝对路径
            abs_path = str(BASE_DIR / value)
            os.environ[var] = abs_path

# 设置HuggingFace环境变量
setup_huggingface_env()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load the secret key from an environment variable.
# For development, a default insecure key is provided if the environment variable is not set.
# In production, DJANGO_SECRET_KEY MUST be set to a strong, unique value.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-jsto-5oth_9(a_xfy#zg@$i$0w47h9a$rw0s&(v#1o5t+s-!*7' # Fallback for dev
)

# SECURITY WARNING: don't run with debug turned on in production!
# Load DEBUG mode from an environment variable. Defaults to False for production.
# Set DJANGO_DEBUG=True in your development environment.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# ALLOWED_HOSTS
# Load allowed hosts from an environment variable (comma-separated string).
# In production, DJANGO_ALLOWED_HOSTS should be set to your domain(s).
ALLOWED_HOSTS_ENV = os.environ.get('DJANGO_ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']  # testserver for Django test client
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] # Production requires DJANGO_ALLOWED_HOSTS to be set


# Application definition

INSTALLED_APPS = [
    'daphne',  # Channels ASGI server，必须放在最前面
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',  # 添加 django-filter
    'channels',  # Django Channels for WebSocket
    'accounts', # 或者 'accounts.apps.AccountsConfig'
    'projects', # 项目管理应用
    'testcases', # 用例管理应用
    'drf_spectacular',
    'corsheaders', # Added for CORS
    'langgraph_integration', # LangGraph Integration App
    'mcp_tools', # MCP Tools App
    'api_keys', # API Keys Management App
    'knowledge', # Knowledge Base Management App
    'testcase_review', # Test Case Review App
    'automation_scripts', # Automation Scripts App
    'prompts', # 提示词管理应用
    'requirements', # 需求评审管理应用
    'orchestrator_integration', # 智能编排集成应用
]

# ASGI 配置（用于 Channels WebSocket）
ASGI_APPLICATION = 'wharttest_django.asgi.application'

# Channels Layer 配置（使用内存后端，生产环境建议使用 Redis）
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Added for CORS, before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wharttest_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wharttest_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# For production, consider using PostgreSQL or MySQL and configure using environment variables.
# Example for PostgreSQL (you would need to install psycopg2-binary):
# if os.environ.get('DATABASE_URL'):
#     import dj_database_url
#     DATABASES = {
#         'default': dj_database_url.config(conn_max_age=600, ssl_require=os.environ.get('DJANGO_DB_SSL', 'False') == 'True')
#     }
# else:

# 数据库配置
# 支持通过环境变量配置数据库类型和连接参数
# DATABASE_TYPE: sqlite (默认) 或 postgres
# DATABASE_PATH: SQLite 文件路径（仅 sqlite 模式）
# POSTGRES_*: PostgreSQL 连接参数（仅 postgres 模式）

DATABASE_TYPE = os.environ.get('DATABASE_TYPE', 'postgres')

if DATABASE_TYPE == 'postgres':
    # PostgreSQL 配置
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'wharttest'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '8919'),
            'OPTIONS': {
                'connect_timeout': 5,
            },
            'CONN_MAX_AGE': 600,  # 连接保持 600 秒（10分钟），避免每次请求重新建立连接
            'CONN_HEALTH_CHECKS': True,  # Django 4.1+ 连接健康检查
        }
    }
else:
    # SQLite 配置（默认，用于本地开发）
    DATABASE_PATH = os.environ.get('DATABASE_PATH')
    if DATABASE_PATH:
        # 使用环境变量指定的路径（Docker部署）
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': DATABASE_PATH,
            }
        }
    else:
        # 使用默认路径（本地开发）
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Consider adding STATIC_ROOT for production 'collectstatic'
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
# 支持通过环境变量配置 MEDIA_ROOT,用于 Docker 部署
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication', # 优先使用 JWT 认证
        'api_keys.authentication.APIKeyAuthentication', # 回退到 API Key 认证
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # 默认需要认证
        'wharttest_django.permissions.DjangoModelPermissions', # 使用扩展的 DjangoModelPermissions
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': (
        'wharttest_django.renderers.UnifiedResponseRenderer',
        # 如果你仍然希望在浏览器中看到 DRF 的可浏览 API 界面进行调试，
        # 可以取消下面这行注释。但请注意，它的输出不会经过 UnifiedResponseRenderer。
        # 'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    # 'DEFAULT_PARSER_CLASSES': [ # 通常 JSONParser 已经默认包含
    #     'rest_framework.parsers.JSONParser',
    # ],
    # 'EXCEPTION_HANDLER': 'your_project_name.utils.custom_exception_handler', # 如果需要更细致的异常处理
}

# CORS Configuration
# In production, DJANGO_CORS_ALLOWED_ORIGINS (comma-separated) should be set.
CORS_ALLOWED_ORIGINS_ENV = os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS')
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',')]
elif DEBUG:
    # Default for development, allows frontend running on common ports
    CORS_ALLOWED_ORIGINS = [
        "http://localhost",       # Nginx default (port 80)
        "http://127.0.0.1",
        "http://localhost:3000",  # React default
        "http://127.0.0.1:3000",
        "http://localhost:5173",  # Vite default
        "http://127.0.0.1:5173",
        "http://localhost:8080",  # Vue/Angular default
        "http://127.0.0.1:8080",
        "http://localhost:8000",  # Django dev server
        "http://127.0.0.1:8000",
    ]
else:
    CORS_ALLOWED_ORIGINS = [] # Production requires DJANGO_CORS_ALLOWED_ORIGINS

# Set to False for production unless your API is truly public and needs to allow all origins.
CORS_ALLOW_ALL_ORIGINS = False # Changed from True

# To allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True # 允许发送认证信息

# 允许的HTTP方法
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# CSRF Trusted Origins - Important if your frontend and backend are on different subdomains or ports
# and you are using session-based authentication or CSRF protection for other parts of your API.
# For JWT based auth like /api/token/, this is less critical but good practice to be aware of.
# Consider loading from DJANGO_CSRF_TRUSTED_ORIGINS in production.
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS')
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(',')]
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = [ # Default for development
        "http://localhost",
        "http://127.0.0.1",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
else:
    CSRF_TRUSTED_ORIGINS = []


# CORS配置已在上面设置

# Simple JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),  # 将访问令牌的有效期延长到12小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # 将刷新令牌的有效期延长到7天
    'ROTATE_REFRESH_TOKENS': True,                 # 刷新令牌时生成新的刷新令牌
    'BLACKLIST_AFTER_ROTATION': False,             # 不使用黑名单
    'UPDATE_LAST_LOGIN': False,                    # 不更新最后登录时间

    'ALGORITHM': 'HS256',                          # 使用HS256算法
    'SIGNING_KEY': SECRET_KEY,                     # 使用Django的SECRET_KEY作为签名密钥

    'AUTH_HEADER_TYPES': ('Bearer',),              # 认证头类型
    'USER_ID_FIELD': 'id',                         # 用户ID字段
    'USER_ID_CLAIM': 'user_id',                    # 用户ID声明
}

# 日志输出目录
LOGS_DIR = BASE_DIR / 'data' / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)  # 自动创建日志目录

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} {name} {process:d} {thread:d} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        # 控制台输出
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # 应用总日志文件 - 使用安全的时间轮转处理器
        'app_file': {
            'level': 'INFO',
            'class': 'wharttest_django.safe_log_handler.SafeTimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'app.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,  # 保留30天
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # 错误日志文件 - 只记录ERROR及以上
        'error_file': {
            'level': 'ERROR',
            'class': 'wharttest_django.safe_log_handler.SafeTimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'error.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 60,  # 错误日志保留60天
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        # Requirements应用专用日志
        'requirements_file': {
            'level': 'DEBUG',
            'class': 'wharttest_django.safe_log_handler.SafeTimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'requirements.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Celery任务日志
        'celery_file': {
            'level': 'INFO',
            'class': 'wharttest_django.safe_log_handler.SafeTimedRotatingFileHandler',
            'filename': str(LOGS_DIR / 'celery.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Django核心日志
        'django': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Requirements应用日志
        'requirements': {
            'handlers': ['console', 'requirements_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'requirements.services': {
            'handlers': ['console', 'requirements_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'requirements.tasks': {
            'handlers': ['console', 'celery_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Celery日志
        'celery': {
            'handlers': ['console', 'celery_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # MCP工具日志
        'mcp_tools': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Knowledge应用日志
        'knowledge': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'knowledge.services': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Testcases应用日志
        'testcases': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'testcases.views': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'testcases.serializers': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Orchestrator集成应用日志(Agent Loop压缩调试)
        'orchestrator_integration': {
            'handlers': ['console', 'app_file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Celery配置
# Celery使用Redis作为broker和backend
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery 6.0+ 启动时重试连接
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery时区设置
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery任务结果配置
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_EXPIRES = 3600  # 结果过期时间(秒)

# Celery任务序列化
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Celery任务配置
CELERY_TASK_TRACK_STARTED = True  # 追踪任务开始状态
CELERY_TASK_TIME_LIMIT = 30 * 60  # 任务超时时间(秒) - 30分钟
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 软超时时间(秒) - 25分钟

# Celery Worker配置
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Worker预取任务数量
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Worker执行多少任务后重启

# Celery日志配置
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# 内部API基础URL配置 - 用于Celery任务等内部服务调用
# 在Docker环境中应设置为 http://backend:8000
# 在本地开发环境中可以使用 http://localhost:8000
BASE_URL = os.environ.get('DJANGO_BASE_URL', 'http://localhost:8000')
